name: Release

on: [push]

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Xcode 13.2.1
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app

    - name: Install Dependencies
      run: brew install mint

    - name: Create XCFramework
      run: mint run unsignedapps/swift-create-xcframework@v2 --platform ios --zip
